#!/usr/bin/env bash
# Boot the current kernel.elf under QEMU.
#
#   scripts/run-qemu.sh             boot with a QEMU window and serial console
#   scripts/run-qemu.sh --headless  serial console only
#   scripts/run-qemu.sh --gdb       pause and listen on :1234 for GDB
#   scripts/run-qemu.sh --defaultqemu use QEMU's normal display frontend
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ELF="${ELF:-$ROOT/build/kernel.elf}"
LIMITS_FILE="$ROOT/build/pippin-limits.env"
LOG_DIR="$ROOT/build/logs"
RUNTIME_LOG="$LOG_DIR/runtime.log"
SHELL_LOG="$LOG_DIR/shell.log"
QEMU_DEBUG_LOG="$LOG_DIR/qemu-debug.log"

mkdir -p "$LOG_DIR"
: > "$RUNTIME_LOG"
: > "$SHELL_LOG"
: > "$QEMU_DEBUG_LOG"

if [[ -f "$LIMITS_FILE" ]]; then
    # Generated by scripts/preflight.sh. Contains numeric/resource-profile
    # values only and is safe to source from this repository's build tree.
    source "$LIMITS_FILE"
else
    PIPPIN_RESOURCE_PROFILE="fallback"
    PIPPIN_QEMU_MEMORY_MB=256
    PIPPIN_BUILD_JOBS=1
fi

printf '[preflight] profile=%s qemu_ram=%sMiB build_jobs=%s\n' \
       "$PIPPIN_RESOURCE_PROFILE" "$PIPPIN_QEMU_MEMORY_MB" "$PIPPIN_BUILD_JOBS" | tee -a "$RUNTIME_LOG"
printf '[logs] runtime=%s qemu_debug=%s shell=%s\n' \
       "$RUNTIME_LOG" "$QEMU_DEBUG_LOG" "$SHELL_LOG" | tee -a "$RUNTIME_LOG"

if [[ ! -f "$ELF" ]]; then
    echo "kernel.elf not found: $ELF (run 'make' first)" >&2
    exit 1
fi

display=gtk,show-menubar=off
gdb=false
disk=false
shell=false
window_server=false
default_qemu=false
for option in "$@"; do
    case "$option" in
        --headless) display=none ;;
        --gdb) gdb=true ;;
        --disk) disk=true ;;
        --shell) shell=true ;;
        --window-server) window_server=true ;;
        --defaultqemu) default_qemu=true ;;
        *) echo "unknown option: $option" >&2; exit 2 ;;
    esac
done

args=(-machine q35 -m "${PIPPIN_QEMU_MEMORY_MB}M")
if [[ "$display" == "none" ]]; then
        args+=( -display none )
elif ! $default_qemu; then
        args+=( -display "$display" )
fi
args+=( -vga std -serial stdio -kernel "$ELF"
        -d guest_errors -D "$QEMU_DEBUG_LOG" )
if $shell || $window_server; then
        UI_SOCKET="$ROOT/build/pippin-ui.sock"
        rm -f "$UI_SOCKET"
        args+=( -chardev "socket,id=pippin_ui,path=$UI_SOCKET,server=on,wait=off"
                -serial chardev:pippin_ui )
fi
if $window_server; then
        MONITOR_SOCKET="$ROOT/build/pippin-monitor.sock"
        rm -f "$MONITOR_SOCKET"
        args+=( -monitor "unix:$MONITOR_SOCKET,server,nowait" )
fi
BACKGROUND_PIDS=()
cleanup() {
        for pid in "${BACKGROUND_PIDS[@]:-}"; do
                kill "$pid" 2>/dev/null || true
                wait "$pid" 2>/dev/null || true
        done
        [[ -n "${UI_SOCKET:-}" ]] && rm -f "$UI_SOCKET"
        [[ -n "${MONITOR_SOCKET:-}" ]] && rm -f "$MONITOR_SOCKET"
}
trap cleanup EXIT INT TERM

if $shell; then
        dotnet run --project "$ROOT/apps/csharp/Pippin.Shell/Pippin.Shell.csproj" \
                --no-build -- --bridge "$UI_SOCKET" \
                > >(sed -u 's/^/[shell] /' | tee -a "$SHELL_LOG" "$RUNTIME_LOG") \
                2> >(sed -u 's/^/[shell:err] /' | tee -a "$SHELL_LOG" "$RUNTIME_LOG" >&2) &
        SHELL_PID=$!
        BACKGROUND_PIDS+=("$SHELL_PID")
fi

# Mirror QEMU's guest-error diagnostics into the host terminal while the
# graphical desktop is alive. This keeps low-level faults visible even after
# Pippin switches away from the VGA text console.
if [[ "$display" != "none" ]]; then
        tail -n 0 -F "$QEMU_DEBUG_LOG" 2>/dev/null \
                | sed -u 's/^/[qemu-debug] /' \
                | tee -a "$RUNTIME_LOG" &
        DEBUG_TAIL_PID=$!
        BACKGROUND_PIDS+=("$DEBUG_TAIL_PID")
fi
if $gdb; then args=(-s -S "${args[@]}"); fi
if $disk; then
        DISK_IMAGE="$ROOT/build/pippin-fat.img"
        [[ -f "$DISK_IMAGE" ]] || { echo "disk image missing: run 'make disk'" >&2; exit 1; }
        args+=( -device ich9-ahci,id=ahci
                -drive "if=none,id=disk,file=$DISK_IMAGE,format=raw"
                -device ide-hd,drive=disk,bus=ahci.0 )
fi

if $shell || $window_server; then
        qemu-system-x86_64 "${args[@]}" \
                > >(sed -u 's/^/[guest] /' | tee -a "$RUNTIME_LOG") \
                2> >(sed -u 's/^/[qemu] /' | tee -a "$RUNTIME_LOG" >&2)
else
        exec qemu-system-x86_64 "${args[@]}"
fi
